### ISSUE TITLE
wont compile of FreeBSD

### ISSUE THREAD

**Issue by justfly1111** [muevoid/Wayherb#5]
bellow is the failed code while compiling:

ninja: Entering directory `build'-usable text snippets that you can use throughout GitHu
[8/10] Compiling C object wayherb.p/src_wayherb.c.o
FAILED: wayherb.p/src_wayherb.c.o 
ccache cc -Iwayherb.p -I. -I.. -I../include -I/-usable text snippets that you can use throughout GitHuusr/local/include/cairo -I/usr/local/include -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/pixman-1 -I/usr/local/include/freetype2 -I/usr/local/include/libdrm -I/usr/local/include/libpng16 -I/usr/local/include/libepoll-shim -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -pthread -D_THREAD_SAFE -MD -MQ wayherb.p/src_wayherb.c.o -MF wayherb.p/src_wayherb.c.o.d -o wayherb.p/src_wayherb.c.o -c ../src/wayherb.c
../src/wayherb.c:101:9: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
        memset(&last_frame, 0, sizeof(struct timespec));
        ^
../src/wayherb.c:101:9: note: include the header <string.h> or explicitly provide a declaration for 'memset'
../src/wayherb.c:109:23: error: use of undeclared identifier 'CLOCK_MONOTONIC_RAW'
        clock_settime(CLOCK_MONOTONIC_RAW, &last_frame);
                      ^
../src/wayherb.c:123:31: error: use of undeclared identifier 'CLOCK_MONOTONIC_RAW'
                clock_settime(CLOCK_MONOTONIC_RAW, &current_frame);
                              ^
1 warning and 2 errors generated.
[9/10] Compiling C object wayherb.p/src_wayland.c.o
ninja: build stopped: subcommand failed.

Also the original herbe had a patch to make it compilable on freebsd but the wayland port is on a whole dif build system and from what i can see isnt necessary cause the flags the patch adds in the x11 version the ones necessary look like theyre already included. if someone can help me itd be greatly appreciated

**Comment by muevoid** [comment]
I don't have freebsd to test on could you link to the patch for original herbe so I can take a look?

**Comment by muevoid** [comment]
Two things actually firstly in src/wayherb.c make sure there is #include "string.h" at the top

Secondly in the meson build file if on bsd i need to see if adding this to the compiler would work:

-D_POSIX_C_SOURCE=199309L

**Comment by muevoid** [comment]
project(
  'wayherb',
  'c',
  license: 'MIT',
)

wayherb_inc = include_directories('include')

cc = meson.get_compiler('c')

cairo = dependency('cairo')
threads = dependency('threads')
wayland_client = dependency('wayland-client')
wayland_cursor = dependency('wayland-cursor')
wayland_protos = dependency('wayland-protocols')

subdir('lib')

wayherb_files = [
  'src/util.c',
  'src/wayherb.c',
  'src/wayland.c',
]

executable(
  'wayherb',
  files(wayherb_files),
  dependencies: [
    cairo,
    client_protos,
    threads,
    wayland_client,
    wayland_cursor,
  ],
  include_directories: [wayherb_inc],
  c_args: ['-D_POSIX_C_SOURCE=199309L'],
  install: true,
)

**Comment by muevoid** [comment]
Try changing your meson.build to the above

**Comment by justfly1111** [comment]
I changed it rm -rf build reconfigured it and ran ninja same issue except this is the new output 

The Meson build system
Version: 0.57.1
Source dir: /usr/home/doeboy1111/git/wayland/wayherb
Build dir: /usr/home/doeboy1111/git/wayland/wayherb/build
Build type: native build
Project name: wayherb
Project version: undefined
C compiler for the host machine: ccache cc (clang 11.0.1 "FreeBSD clang version 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c3fe)")
C linker for the host machine: cc ld.lld 11.0.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/local/bin/pkg-config (1.7.4)
Run-time dependency cairo found: YES 1.16.0
Run-time dependency threads found: YES
Run-time dependency wayland-client found: YES 1.19.0
Run-time dependency wayland-cursor found: YES 1.19.0
Run-time dependency wayland-protocols found: YES 1.20
Program wayland-scanner found: YES (/usr/local/bin/wayland-scanner)
Build targets in project: 1

Found ninja-1.10.2 at /usr/local/bin/ninja
Generating targets:   0%|                                                     Generating targets: 100%|█████████████████████████████████████████████| 1/1 [0                                                                              Writing build.ninja:   0%|                                                   |                                                                              doeboy1111@frigga ~/git/wayland/wayherb $ sudo ninja -C build
root's password:
ninja: Entering directory `build'
[5/10] Compiling C object wayherb.p/src_util.c.o
../src/util.c:48:8: warning: implicit declaration of function 'posix_fallocate' is invalid in C99 [-Wimplicit-function-declaration]
        ret = posix_fallocate(fd, 0, size);
              ^
../src/util.c:67:7: warning: implicit declaration of function 'mkstemp' is invalid in C99 [-Wimplicit-function-declaration]
        fd = mkstemp(tmpname);
             ^
2 warnings generated.
[8/10] Compiling C object wayherb.p/src_wayherb.c.o
FAILED: wayherb.p/src_wayherb.c.o 
ccache cc -Iwayherb.p -I. -I.. -I../include -I/usr/local/include/cairo -I/usr/local/include -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/pixman-1 -I/usr/local/include/freetype2 -I/usr/local/include/libdrm -I/usr/local/include/libpng16 -I/usr/local/include/libepoll-shim -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -pthread -D_THREAD_SAFE -D_POSIX_C_SOURCE=199309L -MD -MQ wayherb.p/src_wayherb.c.o -MF wayherb.p/src_wayherb.c.o.d -o wayherb.p/src_wayherb.c.o -c ../src/wayherb.c
../src/wayherb.c:75:24: error: use of undeclared identifier 'SA_RESTART'
        act_expire.sa_flags = SA_RESTART;
                              ^
../src/wayherb.c:79:24: error: use of undeclared identifier 'SA_RESTART'
        act_ignore.sa_flags = SA_RESTART;
                              ^
../src/wayherb.c:101:9: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
        memset(&last_frame, 0, sizeof(struct timespec));
        ^
../src/wayherb.c:101:9: note: include the header <string.h> or explicitly provide a declaration for 'memset'
../src/wayherb.c:109:23: error: use of undeclared identifier 'CLOCK_MONOTONIC_RAW'
        clock_settime(CLOCK_MONOTONIC_RAW, &last_frame);
                      ^
../src/wayherb.c:123:31: error: use of undeclared identifier 'CLOCK_MONOTONIC_RAW'
                clock_settime(CLOCK_MONOTONIC_RAW, &current_frame);
                              ^
1 warning and 4 errors generated.
[9/10] Compiling C object wayherb.p/src_wayland.c.o
ninja: build stopped: subcommand failed.
doeboy1111@frigga ~/git/wayland/wayherb $

**Comment by muevoid** [comment]
Reclone the repo for a fresh state in src/wayherb.c in both places where it says CLOCK_MONOTONIC_RAW change to CLOCK_MONOTONIC and see if it compiles

**Comment by justfly1111** [comment]
ill try now and am i using the orig or updated meson.build??

**Comment by justfly1111** [comment]
let me try that now and am i using the old or the c

**Comment by muevoid** [comment]
You are using the original meson.build

**Comment by justfly1111** [comment]
so it compiled and installed with the original meson.build from the fresh clone of the repo thank you so much i greatly appreciate

**Comment by muevoid** [comment]
> so it compiled and installed with the original meson.build from the fresh clone of the repo thank you so much i greatly appreciate

No problem glad to help!

**Comment by jbeich** [comment]
Regressed by d7321425731c (see my comment there). Switching to `CLOCK_MONOTONIC` won't help because it isn't adjustable and `clock_settime` (unlike `clock_gettime`) is a privileged operation.

For posterity, here's a workaround:
```
$ git clone https://github.com/muevoid/Wayherb
$ cd Wayherb
$ git checkout v0.2
$ git cherry-pick 50dec245353a 020539313f17
$ meson setup _build
$ meson compile -C _build 
```
